#!/usr/bin/bash

LOCK="$HOME/.config/eww/donotdisturbon"

toggle() {
    if [[ -f "$LOCK" ]]; then
        dunstctl set-paused false
        rm "$LOCK"
    else 
        dunstctl set-paused true
        touch "$LOCK"
    fi
}

startup() {
    if [[ -f "$LOCK" ]]; then
        dunstctl set-paused true
    else 
        dunstctl set-paused false
    fi
}

check() {
    if [[ -f "$LOCK" ]]; then
        echo on
    else 
        echo off
    fi
}

case "$1" in 
    "toggle")
        toggle
        ;;
    "startup")
        startup
        ;;
    "check")
        check
        ;;
esac
