#!/usr/bin/bash

# set your own files and stuff
FILE="/tmp/eww_launch.controlpanel"
EWW="/usr/bin/ewww"
CFG="$HOME/.config/eww/meowayland"

if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

run_eww() {
    ${EWW} -c "$CFG" open controlpanel
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close controlpanel
	rm "$FILE"
fi

