#!/bin/bash
scss_theme="$HOME/.config/eww/carbonmonoxide/colors.scss"
dark="oxocarbon"
light="oxocarbon_light"

switch_theme () {
    echo '@import '"\"$1\"" > $scss_theme
}

current=`cat $scss_theme | awk '{print $2}'`

if [[ $1 == "toggle" ]]; then
    case $current in 
    "\"./themes/${light}.scss\"")
        switch_theme "./themes/$dark.scss"   
        ;;
    "\"./themes/${dark}.scss\"") 
        switch_theme "./themes/$light.scss"
        ;;
    *)
        switch_theme "./themes/$dark.scss"   
        ;;
    esac
else
    if [[ $current == "\"./themes/$dark.scss\"" ]]; then
        echo true
    else 
        echo false
    fi
fi
